# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('cat_img', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=b'', width_field='width_field')),
                ('height_field', models.IntegerField(default=600)),
                ('width_field', models.IntegerField(default=600)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=120, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('info', models.TextField()),
                ('policy', models.TextField()),
                ('ingredients', models.CharField(max_length=256)),
                ('nutrition', models.CharField(max_length=256)),
                ('available', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('img', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=b'', width_field='width_field')),
                ('height_field', models.IntegerField(default=600)),
                ('width_field', models.IntegerField(default=600)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Categories')),
            ],
        ),
    ]
