# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='categories',
            name='height_field',
            field=models.IntegerField(blank=True, default=600, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='width_field',
            field=models.IntegerField(blank=True, default=600, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='height_field',
            field=models.IntegerField(blank=True, default=600, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='width_field',
            field=models.IntegerField(blank=True, default=600, null=True),
        ),
    ]
