# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20170708_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='cat_name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
