# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20170709_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='cat_img',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=b'', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='categories',
            name='height_field',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='categories',
            name='width_field',
            field=models.IntegerField(default=600),
        ),
    ]
