# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20170713_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
