# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=14)),
                ('fb', models.URLField(max_length=256)),
                ('fb_icon', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=b'', width_field='width_field')),
                ('twitter', models.URLField(max_length=256)),
                ('twitter_icon', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=b'', width_field='width_field')),
                ('instagram', models.URLField(max_length=256)),
                ('instagram_icon', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=b'', width_field='width_field')),
                ('height_field', models.IntegerField(default=30)),
                ('width_field', models.IntegerField(default=30)),
            ],
        ),
    ]
