# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=14)),
                ('fb', models.URLField(max_length=256)),
                ('twitter', models.URLField(max_length=256)),
                ('instagram', models.URLField(max_length=256)),
            ],
        ),
    ]
