# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='fb_icon',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=b'', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='height_field',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='instagram_icon',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=b'', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='twitter_icon',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=b'', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='width_field',
            field=models.IntegerField(default=30),
        ),
    ]
