# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='fb_icon',
            field=models.ImageField(default=1, height_field='height_field', upload_to=b'', width_field='width_field'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='instagram_icon',
            field=models.ImageField(default=1, height_field='height_field', upload_to=b'', width_field='width_field'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='twitter_icon',
            field=models.ImageField(height_field='height_field', upload_to=b'', width_field='width_field'),
        ),
    ]
